### PR TITLE
implement cut_at method

### PR DESCRIPTION
**Pull request by popravich**
Basic idea is to replace such code:
[minihttp/server.rs](https://github.com/popravich/minihttp/blob/333992f71b0abe31d2222345e64e6dbc07d60a2b/src/server.rs#L154-L157)

``` rust
let mut SomeStruct = {buf: Buf::new()};
SomeStruct.buf.extend(&self.shared_buf[..size]);
self.shared_buf.consume(size);
```

### CODE REVIEW

**Comment by tailhook** [comment]
split_at is more common name in rust I think

**Comment by popravich** [comment]
True, however most `split_at`s return two parts, `cut_at` splits buffer in place. Rename?

**Comment by tailhook** [comment]
Released in v0.3.5

**Comment by popravich** [comment]
thanks

**Pull request merged**
